<a href="https://colab.research.google.com/github/ywan1416/MAT422/blob/main/HW4_1%2C_4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import eigh

# 4.1.1 Graph Models

A graph consists of nodes and edges. It can be represented as G=(V,E), where: V={v_1,v_2,…,v_n}: the set of nodes (vertices).
E={e_1,e_2,…,e_m}: the set of edges connecting pairs of nodes.
The size of E is often denoted as m=∣E∣. Edges can either be directed or undirected, depending on whether the connection between two nodes has a specific direction.

# 4.1.2 Laplacian Matrix

The Laplacian matrix L of a graph G=(V,E) is defined as L=D-A, where D is the degree matrix (diagonal elements represent node degrees) and A is the adjacency matrix (elements represent edge weights). For diagonal elements L_ii, the value is the degree of node v_i, and for off-diagonal elements L_ij, the value is −E_ij if nodes v _i and v_j are connected, or 0 otherwise. The matrix is symmetric, positive semi-definite, and its smallest eigenvalue is 0, with the corresponding eigenvector being e=[1,1,…,1]^T.

In [ ]:
# Define the nodes and the edges
nodes = [1, 2, 3]
edges = [(1, 2), (2, 3)]  # List of edges

# Number of nodes
n = len(nodes)

# Initialize the adjacency matrix
adj_matrix = np.zeros((n, n))

# Made adjacency matrix based on edges
for edge in edges:
    i, j = edge[0] - 1, edge[1] - 1
    adj_matrix[i][j] = 1
    adj_matrix[j][i] = 1
print("Adjacency Matrix:")
print(adj_matrix)

# Calculate a degree matrix
degree_matrix = np.diag(np.sum(adj_matrix, axis=1))
print("\nDegree Matrix:")
print(degree_matrix)

# Calculate Laplacian matrix
laplacian_matrix = degree_matrix - adj_matrix
print("\nLaplacian Matrix:")
print(laplacian_matrix)

# Calculate Shortest Path Length
shortest_path_length = 2
print("\nShortest Path Length from Node 1 to Node 3:", shortest_path_length)

# Calculate Degree Centrality
degree_centrality = np.sum(adj_matrix, axis=1) / (n - 1)
print("\nDegree Centrality:")
for i, centrality in enumerate(degree_centrality):
    print(f"Node {i + 1}: {centrality:.2f}")


Adjacency Matrix:
[[0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]]

Degree Matrix:
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 1.]]

Laplacian Matrix:
[[ 1. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  1.]]

Shortest Path Length from Node 1 to Node 3: 2

Degree Centrality:
Node 1: 0.50
Node 2: 1.00
Node 3: 0.50


# 4.2 Spectral Graph Bipartitioning

The Laplacian matrix and spectral methods are used for bipartitioning a graph to minimize the connections between two subsets. This approach is widely applied in social network analysis, image segmentation, and other fields.

In [12]:
# Define the adjacency matrix
adj_matrix = np.array([
    [0, 1, 0],  # Node 1
    [1, 0, 1],  # Node 2
    [0, 1, 0],  # Node 3
])

# Calculate the degree matrix
degree_matrix = np.diag(np.sum(adj_matrix, axis=1))

# Calculate the Laplacian matrix
laplacian_matrix = degree_matrix - adj_matrix

# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = eigh(laplacian_matrix)
fiedler_vector = eigenvectors[:, 1]

# Partition nodes based on the sign of the Fiedler vector
partition = [1 if value > 0 else -1 for value in fiedler_vector]

print("Adjacency Matrix:",adj_matrix)
print("\nDegree Matrix:",degree_matrix)
print("\nLaplacian Matrix:",laplacian_matrix)
print("\nEigenvalues of the Laplacian Matrix:",eigenvalues)
print("\nFiedler Vector:",fiedler_vector)
print("\nPartition (1 for V1, -1 for V2):",partition)


Adjacency Matrix: [[0 1 0]
 [1 0 1]
 [0 1 0]]

Degree Matrix: [[1 0 0]
 [0 2 0]
 [0 0 1]]

Laplacian Matrix: [[ 1 -1  0]
 [-1  2 -1]
 [ 0 -1  1]]

Eigenvalues of the Laplacian Matrix: [2.66453526e-15 1.00000000e+00 3.00000000e+00]

Fiedler Vector: [-7.07106781e-01  9.42055475e-16  7.07106781e-01]

Partition (1 for V1, -1 for V2): [-1, 1, 1]
